### PR TITLE
ROX-21047: Widgets are hard to read

### PR DESCRIPTION
**Pull request by ludydoo**
Removed the AZ Memory/CPU utilization - In favor of the capacity planning dashboard

### CODE REVIEW

**Comment by stehessel** [comment]
Can you take a screenshot to review the changes? Alternatively save the updated dashboard under a new name, it will live until the Grafana pod is restarted.

**Comment by stehessel** [comment]
> This dashboard displays the central memory usage over its limits (in %)

I think this is a bit confusing because "over" sounds like "above". How about `This dashboard displays the central memory usage in percentage of the memory limit`.

**Comment by stehessel** [comment]
Can you fix the legend alignment on the left side of the widget? It got messed up in one of the last version bumps.

**Comment by ludydoo** [comment]
> Can you fix the legend alignment on the left side of the widget? It got messed up in one of the last version bumps.

Not sure what you mean

**Comment by ludydoo** [comment]
@stehessel can you have another look?

**Review by stehessel — APPROVED** [review]

**Pull request merged**
