### PR TITLE
ROX-21321: Add ACSCS release dashboard

### PR DESCRIPTION
**Pull request by kurlov**
- `make generate` locally also amended kube mixins files
- Add dashboard which might be convenient during canary upgrade of ACSCS
Screenshot 2023-12-19 at 17 19 37

### CODE REVIEW

**Comment by stehessel** [comment]
> make generate locally also amended kube mixins files

This doesn't happen for me or in CI. What versions of `yq`, `jq` and `jsonnet` are you using? I think we might need to pin them to avoid such inconsistencies.

**Comment by kurlov** [comment]
I use:
- yq 4.21.1
- jq 1.6
- jsonnet, jsonnet-deps v0.20.0

**Comment by stehessel** [comment]
Can you try again with `yq >= 4.40`?

**Comment by kurlov** [comment]
@stehessel this should fix it #185

**Pull request closed without merging**
